---
plex:
  url: "INSERT_PLEX_URL_HERE:32400"
  token: "INSERT_PLEX_TOKEN_HERE"
dizquetv:
  url: "INSERT_DIZQUETV_URL_HERE:8000"
  debug: True
  discord:
    url: "INSERT_DISCORD_WEBHOOK_URL_HERE"
    username: "pmm-dizquetv"
    avatar: "https://github.com/tssgery/pmm-dizquetv/raw/main/avatar/discord-avatar.png"
defaults:
  Movies:
    pad: 10
    fillers:
      - Trailers
    channel_group: Movies
  TV Shows:
    pad: 5
    minimum_days: 7
    fillers:
      - Commercials
    channel_group: TV
libraries:
  Movies:
    Pixar:
      pad: 5
      fillers:
        - Kid Safe Trailers
  TV Shows:
    Friends:
      minimum_days: 31
      random: false
      pad: 2
      channel_name: NBC - Friends
      channel_group: Must See TV
    Lost:
      ignore: True
      random: false
