version: "3"
services:
  pmm-dizquetv:
    container_name: pmm-dizquetv
    image: tssgery/pmm-dizquetv:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /path/to/pmm-dizquetv/config.yml:/config/config.yml:ro
    restart: unless-stopped
    ports:
      - "8000:8000"



